apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fraud-scoring
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes"
  prune: true
  sourceRef:
    kind: GitRepository
    name: fraud-scoring
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-gpg