apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fraud-scoring
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/daviDpaD18/fraud-scoring-deploy
  ref:
    branch: main
  secretRef:
    name: flux-git-auth