apiVersion: v1
kind: GitRepository
metadata:
  name: fraud-scoring
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/daviDpaD18/fraud-scoring-deploy
  ref:
    branch: "${GIT_BRANCH}"